#!/bin/bash

(( $# )) && tmux split-window -d -h "rd $*" \
	 || { RD_ID=$(mktemp -u XXXXXX) ; tmux split-window -d -h "rd -i $RD_ID" ; echo -n "$RD_ID" | xsel -i -b ; } 

#echo -e "rd : rd --fifo | --id | --port | --web [formatter]\nconnect: rd -c | -n | -N" >&2 ; exit 1 ; }

